### ISSUE TITLE
No module named 'minirts'

### ISSUE THREAD

**Issue by tigerneil** [facebookresearch/ELF#1]
```
  File "../rts/game_MC/game.py", line 8, in <module>
    import minirts
ImportError: No module named 'minirts'
```

**Comment by wenying45** [comment]
Need to compile the games at first?

**Comment by wenying45** [comment]
Need to compile the game at first? https://github.com/facebookresearch/ELF/tree/master/rts

**Comment by tigerneil** [comment]
yeah.

**Comment by pedronahum** [comment]
Hi, maybe it would be worth it to update the "How to train section" in readme and remember the reader these steps.
