### ISSUE TITLE
Cannot compile game_TD and game_CF

### ISSUE THREAD

**Issue by Seraphli** [facebookresearch/ELF#10]
Hi

I can compile game_MC successfully, but when I try compiling the other two games, I get this error message:

[cc] wrapper_callback.cc ...
In file included from wrapper_callback.cc:15:0:
ai.h:25:69: error: 'AIComm has not been declared'

**Comment by xiahouzuoxin** [comment]
The same error occur, I defined `AIComm` like `game_MC/ai.h`

```cpp
using Context = ContextT<PythonOptions, ExtGame, Reply>;
using AIComm = AICommT<Context>;
```

**Comment by yukang2017** [comment]
I meet the same error with gcc-4.9.

**Comment by yuandong-tian** [comment]
There are issues in these two games. We will fix this soon.

**Comment by qucheng** [comment]
Should be addressed by the latest commit.
Let me know if you have any problems.

**Comment by Seraphli** [comment]
We can compile `game_TD` now. But while running backend using `make minirts GAME_DIR=../game_TD`, the program terminates with `segmentation fault`.

**Comment by erikluo** [comment]
While running backend using make minirts GAME_DIR=../game_TD or  minirts GAME_DIR=../game_CF ,the program terminates with segmentation fault.

**Comment by erikluo** [comment]
使用Python2.7运行 run.py 报错，这里是需要python3.x的版本吗？

**Comment by qucheng** [comment]
You need Python 3.x to run.

**Comment by qucheng** [comment]
For seg fault issue:
In CF, game modes available is ./minirts flag_selfplay
In TD, game modes available is ./minirts td_simple
selfplay/selfplay2/humanplay are unique to game_MC

**Comment by Seraphli** [comment]
The game can run. But while running `td_simple`, the game stopped with this errors.
```
[replay0][27999] Time/tick: Act: 1.66274ms. Cmd: 0.39482ms. Vis: 0.00257213ms. Total: 2.06013ms.
Cmd: 28004 L 19.16 1.28
[29922]: The game is not in good shape! sum_failed = 250
```

**Comment by qucheng** [comment]
As is said in the readme, add an argument --max_tick 3000

**Comment by Seraphli** [comment]
:ok_hand:
