### ISSUE TITLE
No module named 'rlmethod_forward'

### ISSUE THREAD

**Issue by ATigerWang** [facebookresearch/ELF#12]
Hi,
When running the run.py in the package of rlpytorch, an error arised. It said that no module named 'rlmethod_forward' and it seems that this module does not appear in the project.  How can I solve this problem?  Thank you very much! : )
![default](https://user-images.githubusercontent.com/8135339/28099188-554f3bf6-66ed-11e7-973a-25eed0766809.JPG)

**Comment by qiqiguaitm** [comment]
same problem!

**Comment by yuandong-tian** [comment]
solved by the most recent commit c91c837.
