### ISSUE TITLE
Problems in humanplay

### ISSUE THREAD

**Issue by GaoFangshu** [facebookresearch/ELF#13]
After `./minirts humanplay --vis_after 0`, I can compete with the AI in the webpage. But there seems to be some problems:
* Cannot gather resource. I click on a worker and then click on resource, then the worker just move around the resource but cannot gather it.
* Cannot build tanks or workers. I click on the base and barrack, and have no idea how to build workers or tanks.
* After clicking `Pause` button, cannot resume the game by clicking `Pause` again or clicking somewhere else.

**Comment by ATigerWang** [comment]
There is some recommendations in [https://github.com/facebookresearch/ELF/tree/master/rts](url).
You can do as the shortcut recommends.

**Comment by GaoFangshu** [comment]
Oh, thank you! I should read the whole README next time :stuck_out_tongue_closed_eyes:

**Comment by qucheng** [comment]
Pause has a bug in humanplay. All the button work when loading and playing a replay.
