### ISSUE TITLE
coredump when train models

### ISSUE THREAD

**Issue by qiqiguaitm** [facebookresearch/ELF#14]
when I run the train script run.sh,  it coredumps.
I tried to locate the reason and found that  all coedumps happened  when  it initiallizes the game context,  the line 
GC = game.initialize()   in run.py
I tracebacked the c code in elf, found that  it was caused by  initializing  the random generator _g(_rd());
the  random generators, that 
std::random_device _rd;
std::mt19937 _g;
defined in 
comm_template.h
state_collector.h
and initialized in such code snippets:

CommT(const ContextOptions &context_options, CustomFieldFunc field_func)
      : _context_options(context_options), _total_collectors(0),
      //: _context_options(context_options), _g(_rd()), _total_collectors(0),
        _verbose(context_options.verbose_comm), _field_func(field_func) {

in comm_template.h and 

CustomFieldFunc field_func, SyncSignal *signal, bool verbose)
        : _gid(gid), _hist_len(hist_len), _last_seq(signal->num_games(), -1), _game_counter(signal->num_games(), 0),
          //_g(_rd()), _pool(num_collectors), _verbose(verbose) {
           _pool(num_collectors), _verbose(verbose) {

in state_collector.h

And if I annotate the code initializes the random generator just like above, everything goes well and reproduce the result in the readme.

I'm still trying to find out why?

**Comment by yuandong-tian** [comment]
What is the version of your compiler and operation system?

**Comment by qiqiguaitm** [comment]
gcc version 5.1.1 20150618 (Red Hat 5.1.1-4) (GCC)

**Comment by qiqiguaitm** [comment]
I also suppose it's related to  the version of the gcc compiler and operation system.
what is yours ?

**Comment by yuandong-tian** [comment]
tested on gcc 4.9.3 on CentOs 7 and  clang on MacOS 10.12.

**Comment by qucheng** [comment]
std::random_device internally uses RDRAND instruction. I did some search and it seems there is an issue with RedHat OS, which cannot detect it. This may be related. https://bugzilla.redhat.com/show_bug.cgi?id=996913

**Comment by qiqiguaitm** [comment]
I do not think so because I  tested the code sinppets as below in same gcc and os and worked well.  Strange !

#include <iostream>
#include <random>
class Level
{
public:
   Level();
   int generateTokenType();
   std::random_device _rd;
   std::mt19937 _g;
};
Level::Level(): _g(_rd())
{
}
int Level::generateTokenType()
{
    std::uniform_int_distribution<int> dist(0, 10);
    return dist(_g);
}
int main()
{
  std::random_device _rd;
  std::mt19937 _g(_rd());
//  _g(_rd());
  for(int n = 0; n < 10; n++)
    std::cout << _g() << std::endl;
  Level l;
  std::cout << l.generateTokenType()<<std::endl;
  return 0;
}

**Comment by yuandong-tian** [comment]
We simplified the multithreading code. You can check whether you still have the same issues. Thanks!

**Comment by qiqiguaitm** [comment]
still  not work

**Comment by yuandong-tian** [comment]
@qiqiguaitm did you solve the problem with the latest code?

**Comment by yuandong-tian** [comment]
f268feb9fae77584521208414af06a3ee6728d40 might address your issue.
