### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_minirts)

### ISSUE THREAD

**Issue by ethanluoyc** [facebookresearch/ELF#15]
Hi,

I was attempting to train with the command line arguments specified in the repo's README,
however I was getting this error.

>Traceback (most recent call last):
  File "run.py", line 140, in <module>
    game = load_module(os.environ["game"]).Loader()
  File "/Users/Ethan/dev/github/ELF/rlpytorch/utils.py", line 510, in load_module
    module = __import__(os.path.basename(mod))
  File "./rts/game_MC/game.py", line 8, in <module>
    import minirts
ImportError: dynamic module does not define module export function (PyInit_minirts)

Any idea why this is happening?

**Comment by ppwwyyxx** [comment]
You did not compile the python extension and run the game with the same version of Python.

Try re-compiling everything with:
```bash
PYTHON_CONFIG=/path/to/python/install/dir/bin/python-config make
```
and run with the matching python.

**Comment by ethanluoyc** [comment]
Indeed，fixed by using the right version of Python. Closing this.
