### ISSUE TITLE
Introduction about AI?

### ISSUE THREAD

**Issue by yukang2017** [facebookresearch/ELF#19]
"AI_SIMPLE", "AI_HIT_AND_RUN", "AI_NN", "AI_FLAG_NN", "AI_TD_NN"
Are there any introduction about these 5 different AI?

**Comment by GaoFangshu** [comment]
You can find them in this [arXiv paper](https://arxiv.org/abs/1707.01067) :smiley:

**Comment by qucheng** [comment]
AI_SIMPLE and AI_HIT_AND_RUN are rule-based AI. details in the appendix section.
NN bots are trained bots, connecting with pytorch through a wrapper. 
Flag_NN and TD_NN are for game CF and TD.

**Comment by yukang2017** [comment]
thank you.
