### ISSUE TITLE
Can I use it with TensorFlow?

### ISSUE THREAD

**Issue by GoingMyWay** [facebookresearch/ELF#3]
Sorry to bother you, can I use it with TensorFlow?

**Comment by RafaelMD** [comment]
Good question though.

**Comment by yuandong-tian** [comment]
The simulation part has nothing to do with PyTorch (or whatever DL framework). So you definitely can use it with Tensorflow (using the same main_loop structure mentioned in ./README.md)

**Comment by prannayk** [comment]
Will there be any slowdown due to pipelines that might not be optimized? If used with TF that is?

**Comment by GoingMyWay** [comment]
@yuandong-tian , Thank you, I thought ELF was developed by PyTorch and may not compatible with other DL libraries.

**Comment by yuandong-tian** [comment]
@prannayk I don't have numbers. In any case, you can have a try.

**Comment by yuandong-tian** [comment]
@GoingMyWay it is independent of DL platform. You can use any DL platform you want.
