### ISSUE TITLE
How to evaluate a trained ai like your replay?

### ISSUE THREAD

**Issue by yukang2017** [facebookresearch/ELF#30]
The replay, the battle between trained-ai and build-in ai, really interests me!
How can we evaluate a trained model using .bin file in a html like the video?
In the file ELF/rts/backend/main_loop.cc, I did not find any function supporting trainedAI.

By the way, what was the use of the function commented?
RTSGameOptions ai_vs_mcts(const Parser &parser, string *players)

**Comment by qucheng** [comment]
You can turn on  `--save_prefix [your_prefix]`  to save the replay when you run `run.py`. Then, you can load them following instructions in README replay section.

**Comment by qucheng** [comment]
We have mcts baselines implemented, but it is currently broken after refactoring. We will fix it later.

**Comment by yukang2017** [comment]
Thanks.
But after running run.py with --save_prefix [your_prefix], I got .bin file instead of .rep file.
Would you please give an instruction in detail? What is the command you use?

**Comment by qucheng** [comment]
Sorry, it appears that we removed that switch.
Uncomment game_MC/game.py line 69
# opt.save_replay_prefix = b"replay"

Then it will generate replay files for each game it runs. You might want to evaluate your model with a small number of games.

**Comment by yukang2017** [comment]
Thank you. I got it.
