### ISSUE TITLE
typo in ./atari/game.py, line 81

### ISSUE THREAD

**Issue by pedronahum** [facebookresearch/ELF#32]
Hi.

It seems that there is a typo in ./atari/game.py, line 81:

I think the second "]" after "[input]" should not be there, 
params["action_batchsize"] = int(desc["actor"]["input"]]["_batchsize"])

Best,

Pedro N.

**Comment by yuandong-tian** [comment]
Fixed in https://github.com/facebookresearch/ELF/commit/60d9533fe74b81542df78530626b034914eb9ce9.
