### ISSUE TITLE
How to edit map?

### ISSUE THREAD

**Issue by GaoFangshu** [facebookresearch/ELF#33]
It seems that we can edit map in `ELF/rts/engine/map.h`, do you have any examples about this?

Thank you!

**Comment by qucheng** [comment]
see `ELF/rts/game_MC/cmd_specific.cc`
for a few commands to generate the map.
They will be called at `ELF/rts/game_MC/cmd_specific.cc` in `vector<pair<CmdBPtr, int> > GameDef::GetInitCmds(const RTSGameOptions&)`

**Comment by yuandong-tian** [comment]
You can edit map directly in map.h or you can write your own command that edit the map. For the latter, please check `cmd_specific.cc` to see how you write a command.
