### ISSUE TITLE
How to modify Reward Function For Mini-RTS ?

### ISSUE THREAD

**Issue by yukang2017** [facebookresearch/ELF#34]
"For Mini-RTS, the agent only receives a reward when the game ends (±1 for win/loss)."

But I want to modify the reward function, so that the agent can receives rewards when kill units of the opponent or obtain more resource. 
Would you please tell me where to modify it? Thank you in advance!

**Comment by EasyHard** [comment]
IIUC in game_MC `last_reward` will be mapped to reward in the batch.

**Comment by yukang2017** [comment]
What is the meaning of IIUC?

**Comment by captn3m0** [comment]
>Abbreviation for "If I Understand Correctly."

**Comment by qucheng** [comment]
You are right. The features and rewards are assigned in `ai.cc`
