### ISSUE TITLE
How to enrich Action Space?

### ISSUE THREAD

**Issue by yukang2017** [facebookresearch/ELF#36]
![wechatimg196](https://user-images.githubusercontent.com/24690867/28662738-c81e6e02-72ed-11e7-9f82-11257b0906e5.jpeg)
As described in the paper, there are only 9 commands in action space. And commands about attacks are designed for all units.
How can a agent give commands to a single unit? And how can we add more flexible ones to action space. To be honest, the poor action space is really a drawback of this platform.

**Comment by qucheng** [comment]
Checkout `rts/game_MC/mc_rule_actor.cc` to see how one-hot states are mapped to concrete actions for each unit. They are called by `ai.cc`.
You can definitely come up with your own version.
