### ISSUE TITLE
make rts/backend failed

### ISSUE THREAD

**Issue by pangzhenjia** [facebookresearch/ELF#4]
Hi, sorry to bother.  I failed to make rts/backend, and info was:

In file included from comm_ai.cc:10:
In file included from ./comm_ai.h:13:
./../../vendor/CZMQ-ZWSSock/zwssock.h:13:43: error: unknown type name 'zctx_t'
CZMQ_EXPORT zwssock_t* zwssock_new_router(zctx_t *ctx);
....
....

I'm using mac, and I have brewed install zmq and czmq. No idea why this error occurred, hope to know. Thanks!

**Comment by yuandong-tian** [comment]
Install zmq 4.0.4 and czmq 3.0.2. The version has to match exactly.

**Comment by pangzhenjia** [comment]
Thank you so much!
