### ISSUE TITLE
Nothing displayed in minirts.html for disconnection to rawgit.com

### ISSUE THREAD

**Issue by yukang2017** [facebookresearch/ELF#41]
When I type " ./minirts selfplay --vis_after 0" and open minirts.html, nothing is displayed. And error blog of the browser shows that failed to  connect to rawgit.com.
Do you know how to solve this? Are there alternative solution? Thanks

**Comment by yuandong-tian** [comment]
@ppwwyyxx recently updated zmqsock code.

**Comment by yukang2017** [comment]
Thank you. I make it. But there is a small mistake in README.md of ELF/rts.
"make GAME_DIR=../game_MC" should be "make minirts GAME_DIR=../game_MC"?
