### ISSUE TITLE
[Question:] How to replace opponent AI with my own agent to train in game_MC?

### ISSUE THREAD

**Issue by yukang2017** [facebookresearch/ELF#42]
In game_MC, there are only two build-in AIs which may be not enough for training. So I want to train an agent with an other agent designed by myself to be the opponent. In this case, the game environment would  be able to interact with two agents. 
Are there any possible to support this? If possible, please give me some instructions to do it. It is key to my research. Thank you in advance.

**Comment by qucheng** [comment]
Do you want to build another more complicated rule-based AI?
or do you want to train 2 AIs (e.g. self-play)

**Comment by yukang2017** [comment]
I want to train 2 AIs just as self-play.

**Comment by yukang2017** [comment]
Is it impossible for multi-agent? @qucheng

**Comment by yuandong-tian** [comment]
It is possible. An example interface is like the following: [slides](http://yuandong-tian.com/icml17_workshop.pdf)
I will implement the interface in the next few days.

**Comment by yuandong-tian** [comment]
@yukang2017 addressed by https://github.com/facebookresearch/ELF/commit/6256b570717e4c44dcf9c62da8c69aa2e78321bc

(currently only works for MiniRTS)

**Comment by yuandong-tian** [comment]
@yukang2017 Selfplay is formally in the master branch.
