### ISSUE TITLE
[Question:] How can we visualize trained agent?

### ISSUE THREAD

**Issue by LinZichuan** [facebookresearch/ELF#48]
In ELF/rts/backend/, I run ```./minirts selfplay --vis_after 0``` or ```./minirts humanplay --vis_after 0``` to visualize build-in AI's selfplay or humanplay. But how to load trained A3C agents and visualize agent's play?
It seems that action spaces in game_MC/ and backend/ are not same.

**Comment by yuandong-tian** [comment]
@LinZichuan Currently you can specify `--save_replay_prefix [replay_file_prefix]` to save replays from your training/evaluation/selfplay. Then when you run backend, load the replay with the following command to visualize. 

```
./minirts-backend replay --load_replay [your replay] --vis_after 0
```

**Comment by LinZichuan** [comment]
@yuandong-tian  Thanks. After I add ```--save_replay_prefix```, there are many replay output files. Should I use all of them? like ```--load_replay prefix_*``` ?
By the way, ```./minirts-backend selfplay/humanplay --vis_after 0``` do not work on master branch after the merge.
I tested on Ubuntu 16.04.2, cmake 3.5.1, gcc 5.4.0.

**Comment by yuandong-tian** [comment]
@LinZichuan you can use any of them. They are generated in parallel.

**Comment by yuandong-tian** [comment]
@qucheng might be you can take a look

**Comment by qucheng** [comment]
Should be fixed by latest commit
