### ISSUE TITLE
[Question:] Different opponents

### ISSUE THREAD

**Issue by LinZichuan** [facebookresearch/ELF#50]
Is it possible for the agent to play with different opponents, and get their batch data respectively?
I also wonder where I can find the code about AI_SIMPLE acting. Thanks!

**Comment by yuandong-tian** [comment]
@LinZichuan you want to have separate batch for separate opponents?

**Comment by LinZichuan** [comment]
@yuandong-tian Yes. Is it possible for any opponents? Both build-in AI and selfplay AI?

**Comment by EasyHard** [comment]
`SimpleAI::on_act` @LinZichuan
