### ISSUE TITLE
[Question:] Is the Advantage Actor-Critic Implementation LSTM-safe?

### ISSUE THREAD

**Issue by Jragonmiris** [facebookresearch/ELF#51]
I'm reading the code, and I'm not entirely clear on whether the implementation of ActorCritic (or LearningMethod as an abstract interface in general) is LSTM safe. Correct me if I'm wrong, but it *appears* to me that the environment is meant to call update(batch) as a sort of thread-safe callback at each timestep. But since each game's update doesn't have any ID (that I know of), it's impossible to fetch the relevant LSTM state for forward/backward passes.

The model I want to use requires using heuristics to set a Mask for MaskedSelect anyway, so I know I'll need to edit the code a little, but I'm mostly curious if an LSTM model (e.g. a modified LSTM-A3C from the A3C paper) would work with the current implementation, and if not what I need to change.

**Comment by yuandong-tian** [comment]
@Jragonmiris Whenever `update(batch)` is called, the relevant game threads are blocked and wait for reply. So it is thread-safe and you can do whatever you want with your current data at hand. Other game threads might also run concurrently. 

If you put `--additional_labels id` to the training command line, then each batch contains an additional tensor, i.e., `batch["id"]` that contains game thread id. You can use these id as you want, e.g., to retrieve previous hidden states of your LSTM (or any memory-based approach). 

Alternatively, you can also send them back to C side using the reply mechanism, and have them at hand in the next step.

**Comment by Jragonmiris** [comment]
So to be clear, would I only need to modify the `forward` and `backward` functions to do what's necessary, or is a full modification of `rlmethod` necessary?

**Comment by yuandong-tian** [comment]
@Jragonmiris 
What do you mean by "masked forward/backward"? You probably need to change `rlmethod` as well, since in RNN/LSTM you need to go through consecutive states. 
BTW, I already have one and will release it soon.
