### ISSUE TITLE
[Question:] Multiplayer

### ISSUE THREAD

**Issue by OwenZhu** [facebookresearch/ELF#52]
Hi, my question is it possible that two bots as teammates to confront the third party? and the two bots cannot attack each other.

Thanks!

**Comment by yuandong-tian** [comment]
Selfplay is already the `master` branch. Check `selfplay.py` for details.

**Comment by OwenZhu** [comment]
Thank you so much! 

Do I still need to change the game logic substantially when I try to do self-play between two training bots, and introduce the third party (a rule-based AI)?

**Comment by yuandong-tian** [comment]
1. You don't need to change the game logic substantially if you want a self-play between two trained bot. As an example, check `selfplay.py`. 

2. What do you mean by introducing a third-party bot? Do you want to run a game with three players?

3. You can check logic in `mc_rule_actor.cc` to change the behavior of rule-based AI. You can write your own version by inheriting `AIBase` defined in `rts/game_MC/ai.h`, and following existing AIs, e.g., `AI_SIMPLE`. To make your bot available in Python side, you need to change `rts/game_MC/wrapper_callback.cc`.

**Comment by OwenZhu** [comment]
Yeah. What I mean is how to run a game with three players? Do I need to change the game logic?
