### ISSUE TITLE
Cmake of rts build fails if Thread Building Blocks isn't installed

### ISSUE THREAD

**Issue by Jragonmiris** [facebookresearch/ELF#53]
If you install without Intel TBB installed, and run `make` on the cmake build you get:

> In file included from .../ELF/elf/../elf/state_collector.h:27:0,
>                 from .../ELF/elf/../elf/comm_template.h:27,
>                 from .../ELF/rts/game_MC/wrapper_callback.h:12,
>                 from .../ELF/rts/game_MC/python_wrapper.cc:18:
> .../ELF/elf/../elf/primitive.h:11:36: fatal error: tbb/concurrent_queue.h: No such file or directory
> compilation terminated.

Looking in the file, there's a `USE_TBB` option that's likely not being properly detected or set. Alternatively, the error message could be improved to specify TBB as a dependency.

**Comment by qucheng** [comment]
Hi, in the main README we declare tbb as one of the dependencies.
