### ISSUE TITLE
[Question:] Change units behaviour

### ISSUE THREAD

**Issue by OwenZhu** [facebookresearch/ELF#55]
Sorry to bother you.
In miniRTS game, players can only gain the resource belong to theirselves, but in my research project I really need them to gain the common resources.

So where should I change the code that a resource can be gained by two players?

Also, how to change the properties of units such as capacity of a worker or the gaining speed?

Thanks!

**Comment by yuandong-tian** [comment]
It is hard to summarize this in a short sentence. You can check the class `CmdGather` in `rts/engine/cmd_specific.cc` and start from there. The logic should be fairly easy to understand.

**Comment by OwenZhu** [comment]
Thank you so much!
