### ISSUE TITLE
Experiment GPU information in paper

### ISSUE THREAD

**Issue by JIElite** [facebookresearch/ELF#59]
Excuse me, I saw you use 6 CPU and 1 GPU to train model in the reference paper. 
I want to know which CPU/GPU did you used?

Thank you!

**Comment by yuandong-tian** [comment]
Nvidia K40m 12G

**Comment by yuandong-tian** [comment]
CPU is Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz

**Comment by JIElite** [comment]
Got it! Thank you!
