### ISSUE TITLE
atari build error : No package 'ale' found -- help

### ISSUE THREAD

**Issue by tshh** [facebookresearch/ELF#61]
when i try to build atari with ALE already build and install in python , this is what i got:
atari/build$cmake ..
-- pybind11 v2.3.dev0
-- Checking for module 'ale'
--   No package 'ale' found
CMake Error at /home/tshh/anaconda3/share/cmake-3.9/Modules/FindPkgConfig.cmake:412 (message):
  A required package was not found
Call Stack (most recent call first):
  /home/tshh/anaconda3/share/cmake-3.9/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  CMakeLists.txt:18 (pkg_check_modules)
-- Configuring incomplete, errors occurred!
########################################################################

pip list got result that ALE installed as ale-python-interface
/atari/build$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alabaster (0.7.9)
ale-python-interface (0.0.1)
anaconda-clean (1.0)
anaconda-client (1.5.1)
anaconda-navigator (1.3.1)

# **What should i do ?**help!!!

**Comment by ppwwyyxx** [comment]
ALE needs to be installed by compiling it, not by pip.
Example steps:
```
git clone https://github.com/mgbellemare/Arcade-Learning-Environment ALE && cd ALE
mkdir build && cd build
cmake -DUSE_SDL=OFF -DUSE_RLGLUE=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=/my/installation/prefix ..
make && make install
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/my/installation/prefix/lib/pkgconfig
```

**Comment by tshh** [comment]
Thanks! 
now :
-- Checking for module 'ale'
--   Found ale, version 0.5
but again:
 fatal error: tbb/concurrent_queue.h
I will work on that, thank again.

**Comment by ppwwyyxx** [comment]
tbb is one of the [dependencies](https://github.com/facebookresearch/ELF#dependency).

**Comment by tshh** [comment]
yes, i should have install tbb  .
It's linux learning time again, let me try it for a while.:)

**Comment by tshh** [comment]
took a while to set tbb up.
for a record ,here is how i made it:
download l_tbb_2017.8.239.tar from intel after registration.
untar it
./install_GUI.sh 
after GUI installation
gedit ~/.bashrc 
add:
source yourinstalllocation/intel/tbb/bin/tbbvars.sh intel64 linux

open an new terminal.
