### ISSUE TITLE
Several errors during compiling 

### ISSUE THREAD

**Issue by yukang2017** [facebookresearch/ELF#7]
Everytime I type make gen as follow, I got these errors as follow. 
Do you know why? Thanks in advance.

chenyukang@node02:~/ELF/rts/game_MC$ make gen
[inl] ...
python ../engine/compile_cmds.py --def_file ../engine/cmd --name engine
python ../engine/compile_cmds.py --def_file ../engine/cmd_specific --name engine_specific
python ../engine/compile_cmds.py --def_file cmd_specific --name minirts_specific
chenyukang@node02:~/ELF/rts/game_MC$ make
[dep] ../engine/rule_actor.cc ...
[dep] ../engine/omni_ai.cc ...
[dep] ../engine/game.cc ...
[dep] ../engine/cmd_specific.cc ...
[dep] ../engine/cmd.cc ...
[dep] ../engine/bullet.cc ...
[dep] mc_rule_actor.cc ...
[dep] gamedef.cc ...
[dep] cmd_specific.cc ...
[dep] ai.cc ...
[cc] ai.cc ...
In file included from ../engine/omni_ai.h:13:0,
                 from ai.h:12,
                 from ai.cc:10:
../../vendor/../elf/comm_template.h: In member function ‘void CommStats::Feed(const int64_t&, Generator&)’:
../../vendor/../elf/comm_template.h:99:20: **error**: ‘sleep_for’ is not a member of ‘std::this_thread’
../../vendor/../elf/comm_template.h: In member function ‘bool CommT<DataAddr, Value>::SendDataWaitReply(const Key&, Value&)’:
../../vendor/../elf/comm_template.h:206:13: **error**: ‘sleep_for’ is not a member of ‘std::this_thread’
In file included from ../engine/omni_ai.h:13:0,
                 from ai.h:12,
                 from ai.cc:10:
../../vendor/../elf/comm_template.h: In member function ‘void ContextT<_Options, _Data, _Reply>::Start(ContextT<_Options, _Data, _Reply>::GameStartFunc)’:
../../vendor/../elf/comm_template.h:446:13: error: ‘sleep_for’ is not a member of ‘std::this_thread’
In file included from ../engine/common.h:24:0,
                 from ../engine/cmd.h:13,
                 from ../engine/cmd_receiver.h:13,
                 from ../engine/omni_ai.h:15,
                 from ai.h:12,
                 from ai.cc:10:
../engine/serializer.h: In instantiation of ‘serializer::loader& serializer::operator>>(serializer::loader&, std::map<Key, T>&) [with Key = std::pair<int, int>; T = float; serializer::loader = serializer::loader]’:
../engine/serializer.h:344:27:   recursively required from ‘serializer::loader& serializer::Load(serializer::loader&, T&, Args& ...) [with T = PlayerPrivilege; Args = {int, std::vector<Fog, std::allocator<Fog> >, std::map<std::pair<int, int>, float, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, float> > >, std::map<std::pair<int, int>, std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, std::pair<int, int> > > >}]’
../engine/serializer.h:344:27:   required from ‘serializer::loader& serializer::Load(serializer::loader&, T&, Args& ...) [with T = int; Args = {PlayerPrivilege, int, std::vector<Fog, std::allocator<Fog> >, std::map<std::pair<int, int>, float, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, float> > >, std::map<std::pair<int, int>, std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, std::pair<int, int> > > >}]’
../engine/player.h:148:5:   required from here
../engine/serializer.h:304:13: **error**: ‘class std::map<std::pair<int, int>, float>’ has no member named ‘emplace’
../engine/serializer.h: In instantiation of ‘serializer::loader& serializer::operator>>(serializer::loader&, std::map<Key, T>&) [with Key = std::pair<int, int>; T = std::pair<int, int>; serializer::loader = serializer::loader]’:
../engine/serializer.h:344:27:   recursively required from ‘serializer::loader& serializer::Load(serializer::loader&, T&, Args& ...) [with T = PlayerPrivilege; Args = {int, std::vector<Fog, std::allocator<Fog> >, std::map<std::pair<int, int>, float, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, float> > >, std::map<std::pair<int, int>, std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, std::pair<int, int> > > >}]’
../engine/serializer.h:344:27:   required from ‘serializer::loader& serializer::Load(serializer::loader&, T&, Args& ...) [with T = int; Args = {PlayerPrivilege, int, std::vector<Fog, std::allocator<Fog> >, std::map<std::pair<int, int>, float, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, float> > >, std::map<std::pair<int, int>, std::pair<int, int>, std::less<std::pair<int, int> >, std::allocator<std::pair<const std::pair<int, int>, std::pair<int, int> > > >}]’
../engine/player.h:148:5:   required from here
../engine/serializer.h:304:13: **error**: ‘class std::map<std::pair<int, int>, std::pair<int, int> >’ has no member named ‘emplace’
make: *** [obj/ai.o] **Error** 1

**Comment by yuandong-tian** [comment]
`../../vendor/../elf/comm_template.h:206:13: error: ‘sleep_for’ is not a member of ‘std::this_thread’`

Maybe check your gcc version?

**Comment by yukang2017** [comment]
may I ask which version you use?

**Comment by yukang2017** [comment]
may I ask which version you use?

**Comment by yuandong-tian** [comment]
gcc 4.9.3 works. also clang (Apple LLVM version 8.1.0 (clang-802.0.42)) works.

**Comment by yukang2017** [comment]
thank you!!!
I successfully compile game_MC. 
BUT when I try “./minirts selfplay --vis_after 0”，nothing happen in "./rts/frontend/minirts.html".
Do you know why?

**Comment by yuandong-tian** [comment]
Make sure that your computer does not block port 8000...

**Comment by yukang2017** [comment]
My port 8000 is well. I can connect to 127.0.0.1:8000, but the webpage is all blank and the file "./rts/frontend/minirts.html" has not been modified...

**Comment by yuandong-tian** [comment]
did you enable javascript in your browser?

**Comment by yukang2017** [comment]
![wechatimg146](https://user-images.githubusercontent.com/24690867/28060288-4f6d47bc-6659-11e7-9149-51c4b097569c.jpeg)
I am sure my javascript is enable. This is what I get in the browser. There are sliders, but nothing else.

**Comment by GaoFangshu** [comment]
When I run `make gen`:
```
$ make gen
[inl] ...
python ../engine/compile_cmds.py --def_file ../engine/cmd --name engine
python ../engine/compile_cmds.py --def_file ../engine/cmd_specific --name engine_specific
python ../engine/compile_cmds.py --def_file cmd_specific --name minirts_specific
```
And then `make`:
```
$ make
bash: python-config: command not found
[dep] ../engine/rule_actor.cc ...
bash: python-config: command not found
[dep] ../engine/cmd_specific.cc ...
bash: python-config: command not found
[dep] ../engine/cmd.cc ...
bash: python-config: command not found
[dep] ../engine/bullet.cc ...
bash: python-config: command not found
[dep] ../engine/ai.cc ...
bash: python-config: command not found
[dep] ../engine/game.cc ...
bash: python-config: command not found
[dep] wrapper_callback.cc ...
bash: python-config: command not found
[dep] python_wrapper.cc ...
bash: python-config: command not found
[dep] mc_rule_actor.cc ...
bash: python-config: command not found
[dep] gamedef.cc ...
bash: python-config: command not found
[dep] cmd_specific.cc ...
bash: python-config: command not found
[dep] ai.cc ...
bash: python-config: command not found
[cc] ai.cc ...
bash: python-config: command not found
[cc] cmd_specific.cc ...
bash: python-config: command not found
[cc] gamedef.cc ...
bash: python-config: command not found
[cc] mc_rule_actor.cc ...
bash: python-config: command not found
[cc] python_wrapper.cc ...
In file included from ../../vendor/pybind11/pytypes.h:12:0,
                 from ../../vendor/pybind11/cast.h:13,
                 from ../../vendor/pybind11/attr.h:13,
                 from ../../vendor/pybind11/pybind11.h:36,
                 from python_wrapper.cc:10:
../../vendor/pybind11/common.h:99:20: fatal error: Python.h: No such file or directory
compilation terminated.
Makefile:75: recipe for target 'obj/python_wrapper.o' failed
make: *** [obj/python_wrapper.o] Error 1
```
I'm not sure what the problem is and how can I solve it :(

**Comment by GaoFangshu** [comment]
When I run `make minirts GAME_DIR= ../game_MC`, there comes a error:
```
$ make minirts GAME_DIR= ../game_MC
Linking ...
/usr/bin/ld: cannot find -ltbb
collect2: error: ld returned 1 exit status
Makefile:70: recipe for target 'minirts' failed
make: *** [minirts] Error 1
```
I guess there are something I haven't installed. But do you have any idea on this problem? Thank you.

**Comment by yuandong-tian** [comment]
@GaoFangshu you need to install libtbb first.

**Comment by yuandong-tian** [comment]
@yukang2017 you can try other ports as well by changing https://github.com/facebookresearch/ELF/blob/master/rts/backend/main_loop.cc#L46

**Comment by qucheng** [comment]
@yukang2017 Can you check console in brower for any error logs there?

**Comment by yukang2017** [comment]
@qucheng @yuandong-tian Thank you very much for help.
I tried other port, but nothing changed. In the console, the error log is:
Firefox can’t establish a connection to the server at ws://localhost:8000/.
WebSocket closed ws://localhost:8000
![wechatimg147](https://user-images.githubusercontent.com/24690867/28098403-a756980e-66e8-11e7-8691-a23afe99e1f8.jpeg)

**Comment by yukang2017** [comment]
@GaoFangshu 
try
sudo apt-get install libtbb-dev

**Comment by GaoFangshu** [comment]
@yuandong-tian @yukang2017  Thank you very much, it works now!

**Comment by GaoFangshu** [comment]
@yukang2017 I use Chrome, and it works well. Maybe you can try Chrome.

**Comment by yukang2017** [comment]
@GaoFangshu Thanks. I tried chrome, but the result is same.
![wechatimg149](https://user-images.githubusercontent.com/24690867/28099278-0fd70f44-66ee-11e7-9765-0e0e9402e2f4.jpeg)

**Comment by qucheng** [comment]
You need to run ./minirts selfplay --vis_after 0 first then open the webpage

**Comment by JiachenLiu** [comment]
Everytime I type make gen as follow, I got these errors as follow.
Do you know why? Thanks in advance
myubuntu@myubuntu:~/ELF-master/rts/game_MC$ make gen
[inl] ...
python ../engine/compile_cmds.py --def_file ../engine/cmd --name engine
Traceback (most recent call last):
  File "../engine/compile_cmds.py", line 130, in <module>
    output = open(cmd_header, "w")
PermissionError: [Errno 13] Permission denied: '../engine/cmd.gen.h'
Makefile:89: recipe for target 'gen' failed
make: *** [gen] Error 1

**Comment by yukang2017** [comment]
try:
sudo make gen

**Comment by JiachenLiu** [comment]
thank you!!!
I successfully compile game_MC.
BUT when I try "make minirts GAME_DIR=../game_MC"
[cc] main_loop.cc ...
In file included from comm_ai.h:13:0,
                 from main_loop.cc:19:
../../vendor/CZMQ-ZWSSock/zwssock.h:13:43: error: ‘zctx_t’ was not declared in this scope
 CZMQ_EXPORT zwssock_t* zwssock_new_router(zctx_t *ctx);
                                           ^
../../vendor/CZMQ-ZWSSock/zwssock.h:13:51: error: ‘ctx’ was not declared in this scope
 CZMQ_EXPORT zwssock_t* zwssock_new_router(zctx_t *ctx);
                                                   ^
In file included from main_loop.cc:19:0:
comm_ai.h:23:5: error: ‘zctx_t’ does not name a type
     zctx_t* _ctx;
     ^
comm_ai.h: In constructor ‘TCPAI::TCPAI(PlayerId, int, char*, CmdReceiver*)’:
comm_ai.h:48:9: error: ‘_ctx’ was not declared in this scope
         _ctx = zctx_new();
         ^
comm_ai.h:48:25: error: ‘zctx_new’ was not declared in this scope
         _ctx = zctx_new();
                         ^
comm_ai.h:49:40: error: ‘zwssock_new_router’ cannot be used as a function
         _sock = zwssock_new_router(_ctx);
                                        ^
comm_ai.h: In destructor ‘TCPAI::~TCPAI()’:
comm_ai.h:68:18: error: ‘_ctx’ was not declared in this scope
    zctx_destroy(&_ctx);
                  ^
comm_ai.h:68:22: error: ‘zctx_destroy’ was not declared in this scope
    zctx_destroy(&_ctx);
                      ^
Makefile:57: recipe for target 'obj/main_loop.o' failed
make: *** [obj/main_loop.o] Error 1
Do you know why?

**Comment by yukang2017** [comment]
what is your gcc and g++ version?
@JiachenLiu

**Comment by JiachenLiu** [comment]
gcc-4.9.3

**Comment by qucheng** [comment]
@JiachenLiu  What's your version of ZMQ and CZMQ? See https://github.com/facebookresearch/ELF/tree/master/rts , specific version is required right now

**Comment by qucheng** [comment]
backend folder is just for command line runs and front end visualizations. Yon can train model with only C++ library compiled

**Comment by JiachenLiu** [comment]
Thank you，I get it. @qucheng
