### ISSUE TITLE
No module named 'go_game'

### ISSUE THREAD

**Issue by CoolPhilChen** [facebookresearch/ELF#73]
Hi! I was trying to run darkforestGo , but after I typed 
`sh ./train_df.sh --gpu 1 --no_leaky_relu --list_file ./go/sample1.sgf`, 
I got the following error
`Traceback (most recent call last):
  File "train.py", line 20, in <module>
    env, all_args = load_env(os.environ, trainer=trainer, runner=runner)
  File "/home/Phil/ELF/rlpytorch/model_loader.py", line 109, in load_env
    game = load_module(envs["game"]).Loader()
  File "/home/Phil/ELF/rlpytorch/model_loader.py", line 18, in load_module
    module = __import__(os.path.basename(mod))
  File "./go/game.py", line 10, in <module>
    import go_game as go
ModuleNotFoundError: No module named 'go_game'`

Could you @yuandong-tian  please help me? Thanks very much!

**Comment by qucheng** [comment]
You need to compile /go directory first. See instructions in go folder with cmake

**Comment by CoolPhilChen** [comment]
It works now! Thanks you very much @qucheng !
