### ISSUE TITLE
Compiled with g++ 7.1: what() regex_error

### ISSUE THREAD

**Issue by Seraphli** [facebookresearch/ELF#9]
After compiling game_MC and backend with g++ 7.1 on ubuntu 14.04, I get this error message:

what() regex_error
core dump

Is this because g++ does not fully support regex?

**Comment by yuandong-tian** [comment]
ok. What is your command line used to run backend?

**Comment by Seraphli** [comment]
Tried `./minirts selfplay` and `./minirts humanplay --vis_after 0`.

**Comment by yuandong-tian** [comment]
ELF works on gcc 4.9.3 or clang (Apple LLVM version 8.1.0 (clang-802.0.42)). Could you try these compilers? Let me know if you have issues.

**Comment by Seraphli** [comment]
g++ 4.9.4 works. We did not realize we were using g++ 4.8.
